orca_url: "https://api.mainnet.orca.so/v1/whirlpool/list"
raydium_url: "https://api-v3.raydium.io/pools/info/list?poolType=concentrated&poolSortField=default&sortType=desc&pageSize=1000&page=1"
apr_min: 10     # in %
apr_max: 1000   # in %
tvl_min: 10     # in kUSD
default_display_limit: 10
include: 
  - "btc"
  - "cad"
  - "chf"
  - "dai"
  - "eth"
  - "eur"
  - "inf"     # https://app.sanctum.so/infinity
  - "isc"     # https://isc.money/
  - "jlp"     # https://jup.ag/perps-earn
  - "link"
  - "lst"
  - "pai"     # https://parrot.fi/mint/
  - "sol"
  - "usd"
  - "uxd"
  - "xau"
risk_include: 
  - "HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC"  # ai16z (DefAI)
  - "KENJSUYLASHUMfHyy5o4Hp2FdNqZg1AsUPhfH2kYvEP"   # Griffain  (DefAI)
  - "HBB111SCo9jkCejsZfz8Ec8nH7T6THF8KEKSnvwT6XK6"  # HBB
  - "9McvH6w97oewLmPxqQEoHUAv3u5iYMyQ9AeZZhguYf1T"  # HeyAnon  (DefAI)
  - "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux"   # HNT
  - "iotEVVZLEywoTn1QdwNPddxPWszn3zFhEot3MfL9fns"   # IOT    - Part of Helium
  - "GQQ7zcP3a5dqrMYaD7BPdPd9Ksxcm6BgkcfnBKWsqcWn"  # kotopia
  - "mb1eu7TzEc71KxDpsmsKoucSSuuoGLv1drys1oP2jh6"   # MOBILE - Part of Helium, actively running in the USA
  - "3N2ETvNpPNAxhcaXgkhKoY1yDnQfs41Wnxsx5qNJpump"  # NEUR (DefAI)
  - "nosXBVoaCTtYdLvKY6Csb4AC8JCdQKKAaWYtx2ZMoo7"   # NOSANA - Decentralized GPU sharing, launch in Jan 2025 - 2x inflation
  - "GekTNfm84QfyP2GdAHZ5AgACBRd69aNmgA5FDhZupump"  # ORBIT ($GRIFT) (DefAI)
  - "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE"   # ORCA
  - "BEJ3VtRiBJ7wqGwAKQeKPgwCsV37QZw8nFZYsYumXrWa"  # POLY (Polytrader)
  - "rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof"   # RENDER
  - "DLUNTKRQt7CrpqSX1naHUYoBznJ9pvMP65uCeWQgYnRK"  # SOLC
  - "8x5VqbHA8D7NkD52uNuS5nnt3PwA8pLD34ymskeSo2Wn"  # Zerebro (DefAI)
  - "ZEUS1aR7aX8DFFJf5QjWj2ftDDdNTroMNGo8YoQm3Gq"   # ZEUS   - 3x inflation during the next 2 years - Decentralized BTC on Solana 22k $ZEUS needs to be staked for each minted zBTC
  #
  # ---=== 2025 ===---
  # - "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN"   # JUP    - 5x inflation, but clever staking mechanism for voting, rewards and future airdrops (there is a proposal to reduce max supply from 10B to 7B, reducing 7x inflation to 5x) Check again in Feb 2025
  # - "Grass7B4RdKfBCjTKgSqnXkqjwiGvQyFbuSCUJr3XXjs"  # GRASS - 4x inflation. Check again in Q2 2025
  # - "TNSRxcUxoT9xBG3de7PiJyTDYu7kskLqcpddxnEJAS6"   # TNSR (Tensor) - crappy, 3x inflation in 3 years. Check again in Q3 2025
  # - "MEFNBXixkEbait3xn9bkm8WsJzXtVsaJEn4c8Sam21u"   # ME - 7.5x inflation. Check again the vesting schedule in Q3 2025
  # - "cloudkc4ane7heqcppe3yhnznrxhmimj4myauqyhfzau"  # CLOUD - crappy, 5.5x inflation in 3 years. Check again in Q3 2025
  # - "jtojtomepa8bep8auqc6ext5frijwffmwqx2v2f9mcl"   # JTO (Jito) - 4x inflation. Check again in Q4 2025
  # ---=== 2026 ===---
  # - "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ"  # W (Wormhole) - crap, > 5x inflation during the next 4 years. Check again in Q2 2026
  # - "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3"  # PYTH - ultra crap, > 6x inflation in 3 years. Check again in Q3 2026
  # - "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS"   # KMNO (Kamino) - ultra crap, 10x inflation, unclear vesting schedule. Check again in Q3 2026
  # ---=== 2027 ===---
  # - "4LLbsb5ReP3yEtYzmXewyGjcir5uXtKFURtaEUVC2AHs"  # PRCL (Parcl) - ultra crap, 8x inflation over a longer period. Check again in Q1 2027
  # - "DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7"  # DRIFT - ultra crap, 6x inflation 
exclude: 
  - "aether"
  - "babybtc"
  - "beth"
  - "blst"     # Blast royale - https://www.blastroyale.com/
  - "btcat"
  - "citadail"
  - "gst-sol"
  - "kumasol"
  - "mockjup"
  - "neur"
  - "onlyblink"
  - "pisces"
  - "plink"
  - "sobtc"
  - "soladog"
  - "solama"
  - "solami"
  - "solamo"
  - "solana"
  - "solape"
  - "solaris"
  - "solbird"
  - "solbro"
  - "solc"
  - "solcade"
  - "solcat"
  - "solcc"
  - "solcex"
  - "sole"
  - "solfnd"
  - "solid"
  - "solnic"
  - "sols"
  - "solsponge"
  - "solx"
  - "solzilla"
addr_exclude: 
  - "EtBc6gkCvsB9c6f5wSbwG8wPjRqXMB5euptK6bqG1R4X"  # BTC - Batcat