url: "https://api.mainnet.orca.so/v1/whirlpool/list"
apr_min: 30     # in %
apr_max: 10000  # in %
tvl_min: 10     # in kUSD
default_display_limit: 10
include: 
  - "usd"
  - "eur"
  - "sol"
  - "eth"
  - "btc"
  - "uxd"
  - "cad"
  - "chf"
  - "xau"
  - "hbb"
  - "dai"
  - "lst"
  - "link"
  - "grt"
  - "jlp"
  - "render"
risk_include: 
  - "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ"  # W (Whirpool)
  - "ZEUS1aR7aX8DFFJf5QjWj2ftDDdNTroMNGo8YoQm3Gq"   # ZEUS
  - "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN"   # JUP
  - "DLUNTKRQt7CrpqSX1naHUYoBznJ9pvMP65uCeWQgYnRK"  # SOLC
  - "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3"  # PYTH
  - "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux"   # HNT
  - "TNSRxcUxoT9xBG3de7PiJyTDYu7kskLqcpddxnEJAS6"   # TNSR (Tensor)
exclude: 
  - "solape"
  - "sols"
  - "solzilla"
  - "solfnd"
  - "solama"
  - "solana"
  - "sobtc"
  - "solnic"
  - "solbird"
  - "sole"
  - "mockjup"
  - "solami"
  - "solsponge"
  - "solcade"
  - "solamo"
  - "plink"
  - "gst-sol"
  - "soladog"
  - "solbro"
  - "solx"
  - "solcc"
  - "solc"
addr_exclude: 
  - "EtBc6gkCvsB9c6f5wSbwG8wPjRqXMB5euptK6bqG1R4X"  # BTC - Batcat